app_name: patient-service
adminUrl: http://localhost:8083
serviceUrl: http://localhost:8082
doctorServiceUrl: "http://localhost:8084"
patientServiceUrl: "http://localhost:8085"
appointmentServiceUrl: "http://localhost:8086"
notificationServiceUrl: "http://localhost:8088"
authServiceUrl: "http://localhost:8087"
MONGO_URI: mongodb://root:rootpassword@localhost:27017/healthcare?authSource=admin
KAFKA_BOOTSTRAP_SERVER: localhost:9092
KAFKA_TOPIC: appointments
JWT_SECRET: aHR0cHM6Ly93d3cueW91YmlsdW1hbWVyaWNhLmNvbS9sb2dpbi8=
KAFKA_GROUP_ID: appointment-notifications-group
MAIL_SERVER_HOST: smtp.gmail.com
MAIL_SERVER_PORT: 587

spring:
  application:
    name: ${app_name}

  boot:
    admin:
      client:
        enabled: true
        instance:
          name: ${app_name}
          service-url: ${patientServiceUrl}
        url: ${adminUrl}
        auto-registration: true
  data:
    mongodb:
      uri: ${MONGO_URI}

logging:
  level:
    org:
      springframework:
        web: DEBUG
        servlet: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
      enable:
        include: health

server:
  port: ${PATIENT_SERVICE_PORT:8085}
