spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:9090
              - http://localhost:5173
              - http://localhost:8081
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
  application:
    name: gateway-service
  boot:
    admin:
      client:
        enabled: true
        instance:
          name: Gateway Service
          service-url: http://localhost:8082
        url: http://localhost:8083
        auto-registration: true

  main:
    web-application-type: reactive

  logging:
    level:
      org.springframework.cloud.gateway: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
      enable:
        include: health

server:
  port: ${GATEWAY_SERVICE_PORT}

jwt:
  secret: ${JWT_SECRET}
gateway:
  services:
    default:
      circuitBreakerCofig:
        timeout-seconds: 2
        failure-rate-threshold: 40.0
        wait-duration-open-seconds: 5
        sliding-window-size: 50

    doctor-service:
      circuitBreakerCofig:
        timeout-seconds: 2
        failure-rate-threshold: 40.0
        wait-duration-open-seconds: 5
        sliding-window-size: 50
      router:
        path: "/api/v1/doctor/**"
        fallback-uri: "/fallback/doctor"
        uri: "http:/localhost:8084"
    patient-service:
      circuitBreakerCofig:
        timeout-seconds: 2
        failure-rate-threshold: 40.0
        wait-duration-open-seconds: 5
        sliding-window-size: 50
      router:
        path: "/api/v1/patient/**"
        fallback-uri: "/fallback/patient"
        uri: "http://localhost:8085"

    appointment-service:
      circuitBreakerCofig:
        timeout-seconds: 2
        failure-rate-threshold: 40.0
        wait-duration-open-seconds: 5
        sliding-window-size: 50
      router:
        path: "/api/v1/appointments/**"
        fallback-uri: "/fallback/appointment"
        uri: "http://localhost:8086"

    auth-service:
      circuitBreakerCofig:
        timeout-seconds: 2
        failure-rate-threshold: 40.0
        wait-duration-open-seconds: 5
        sliding-window-size: 50

      router:
        path: "/api/auth/**"
        fallback-uri: "/fallback/auth"
        uri: "http://localhost:8087"
  open-api-endpoints:
    - "/api/auth/register"
    - "/api/auth/signin"
