spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:9090
              - http://localhost:5173
              - http://localhost:8081
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
  application:
    name: gateway-service
  boot:
    admin:
      client:
        enabled: true
        instance:
          name: Gateway Service
          service-url: http://gateway-service:8080
        url: http://admin-service:8080
        auto-registration: true

  main:
    web-application-type: reactive

  logging:
    level:
      org.springframework.cloud.gateway: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
      enable:
        include: health

server:
  port: ${GATEWAY_SERVICE_PORT}

jwt:
  secret: ${JWT_SECRET}
gateway:
  router:
    services:
      doctor-service:
        path: "/api/v1/doctor/**"
        fallback-uri: "/fallback/doctor"
        uri: "http://doctor-service:8080"

      patient-service:
        path: "/api/v1/patient/**"
        fallback-uri: "/fallback/patient"
        uri: "http://patient-service:8080"

      appointment-service:
        path: "/api/v1/appointments/**"
        fallback-uri: "/fallback/appointment"
        uri: "http://appointment-service:8080"

      auth-service:
        path: "/api/auth/**"
        fallback-uri: "/fallback/auth"
        uri: "http://auth-service:8080"

    open-api-endpoints:
      - "/api/auth/register"
      - "/api/auth/signin"
