#Changing Variables
app_name: gateway-service
allowedOrigins:
  - http://localhost:9090
  - http://localhost:5173
  - http://localhost:8081
adminUrl: http://localhost:8083
serviceUrl: http://localhost:8082
doctorServiceUrl: "http://localhost:8084"
patientServiceUrl: "http://localhost:8085"
appointmentServiceUrl: "http://localhost:8086"
authServiceUrl: "http://localhost:8087"
#  default strucutres for internl use/
spring:
  application:
    name: ${app_name}
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:9090
              - http://localhost:5173
              - http://localhost:8081
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
  boot:
    admin:
      client:
        enabled: true
        instance:
          name: {app_name}
          service-url: ${serviceUrl}
        url: ${adminUrl}
        auto-registration: true
  main:
    web-application-type: reactive
  logging:
    level:
      org.springframework.cloud.gateway: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: "*"
      enable:
        include: health
server:
  port: ${GATEWAY_SERVICE_PORT}
jwt:
  secret: ${JWT_SECRET}

gateway:
  services:
    default:
      circuitBreakerCofig:
        timeout-seconds: 2
        failure-rate-threshold: 40.0
        wait-duration-open-seconds: 5
        sliding-window-size: 50

    doctor-service:
      circuitBreakerCofig:
        timeout-seconds: 2
        failure-rate-threshold: 40.0
        wait-duration-open-seconds: 5
        sliding-window-size: 50
      router:
        path: "/api/v1/doctor/**"
        fallback-uri: "/fallback/doctor"
        uri: ${doctorServiceUrl}
    patient-service:
      circuitBreakerCofig:
        timeout-seconds: 2
        failure-rate-threshold: 40.0
        wait-duration-open-seconds: 5
        sliding-window-size: 50
      router:
        path: "/api/v1/patient/**"
        fallback-uri: "/fallback/patient"
        uri:  ${patientServiceUrl}
    appointment-service:
      circuitBreakerCofig:
        timeout-seconds: 2
        failure-rate-threshold: 40.0
        wait-duration-open-seconds: 5
        sliding-window-size: 50
      router:
        path: "/api/v1/appointments/**"
        fallback-uri: "/fallback/appointment"
        uri: ${appointmentServiceUrl}

    auth-service:
      circuitBreakerCofig:
        timeout-seconds: 2
        failure-rate-threshold: 40.0
        wait-duration-open-seconds: 5
        sliding-window-size: 50
      router:
        path: "/api/auth/**"
        fallback-uri: "/fallback/auth"
        uri: ${authServiceUrl}
  open-api-endpoints:
    - "/api/auth/register"
    - "/api/auth/signin"